// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://idnogsikdoytwfocfily.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imlkbm9nc2lrZG95dHdmb2NmaWx5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5NjA5OTUsImV4cCI6MjA2NTUzNjk5NX0.ijJzE6-iQeD5BxXW_b5-UCojGnJZ2T4wmDNtWRpYPCA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);